Integrar redis en agave
cuenca-mx/agave pull request #17
Opened 2020-12-01 19:06 UTC by Gleekzone

Voy a ponerlo como draft

2020-12-02 22:54 UTC, felipaoo requested changes

2020-12-02 22:54 UTC, felipaoo commented on agave/filters.py
> +import datetime as dt
conviene crear un nuevo módulo que se llame `filters` y dentro dos archivos `mongodb` y `redis` para ahí colocar estas funciones.

2020-12-02 22:54 UTC, felipaoo commented on agave/filters.py
> +        return filters
esto para que es?

2020-12-02 22:54 UTC, felipaoo commented on agave/repositories/__init__.py
> +from .base_redis import BaseModel
Separar en módulos independientes uno para mongo y otro para redis y colocar todas las clases y utilidades necesarias para cada DBM dentro de su módulo correspondiente

2020-12-02 22:54 UTC, felipaoo commented on agave/repositories/base_redis.py
> +import datetime as dt
mover este archivo a su módulo correspondiente

2020-12-02 22:54 UTC, felipaoo commented on agave/repositories/helpers_redis.py
> +from rom import Column
mover a su modulo correspondiente

2020-12-02 22:54 UTC, felipaoo commented on agave/repositories/redis_repository.py
> +from typing import Callable
mover a su módulo correspondiente

2020-12-02 22:54 UTC, felipaoo commented on agave/repositories/redis_repository.py
> +            raise ModelDoesNotExist
😄

2020-12-02 22:54 UTC, felipaoo commented on agave/repositories/redis_repository.py
> +            limit = params.page_size
esta lógica está repetida en la clase de mongo_repository, conviene moverla a la clase base

2020-12-02 22:54 UTC, felipaoo commented on agave/repositories/redis_repository.py
> +            items=list(items),
reutliza `results`

2020-12-02 22:54 UTC, felipaoo commented on examples/chalicelib/resources/resources_redis/accounts_redis.py
> +import datetime as dt
como los resources de ejemplos y los fixtures son los mismos debemos mejor unificarlos de tal forma que podamos tener un solo conjunto de resources y fixtures. Esto ayudará a no repetir código u olvidar testear algo si e es que creamos nuevos tests

recomiendo usar `@pytest.mark.parametrize`. en especial parametrización indirecta: https://docs.pytest.org/en/stable/example/parametrize.html#indirect-parametrization

Así solo tendremos un archivo de test que va a probar todo

2020-12-02 23:04 UTC, Gleekzone commented on examples/chalicelib/resources/resources_redis/accounts_redis.py
> +class AccountFormatter:
Ya no esta, hahaha creo que estaba en la primera version

2020-12-02 23:09 UTC, Gleekzone commented on agave/repositories/redis_repository.py
> +            limit = params.page_size
de la 29-34 si, de la 35-39 el query cambia. Haces referencia a las lineas 29-34?

2020-12-02 23:10 UTC, Gleekzone commented on agave/repositories/redis_repository.py
> +            items=list(items),
no entiendo este comentario :/

2020-12-02 23:22 UTC, Gleekzone commented on agave/repositories/redis_repository.py
> +            raise ModelDoesNotExist
👍

2020-12-02 23:22 UTC, Gleekzone commented on agave/repositories/redis_repository.py
> +from typing import Callable
👍

2020-12-02 23:22 UTC, Gleekzone commented on agave/repositories/helpers_redis.py
> +from rom import Column
👍

2020-12-02 23:22 UTC, Gleekzone commented on agave/repositories/base_redis.py
> +import datetime as dt
👍

2020-12-04 18:20 UTC, felipaoo requested changes

2020-12-04 19:12 UTC, Gleekzone commented on agave/collections/redis/base_redis.py
> +import datetime as dt
👍

2020-12-04 19:13 UTC, Gleekzone commented on agave/collections/redis/filters_redis.py
> +import datetime as dt
👍

2020-12-04 19:13 UTC, Gleekzone commented on agave/collections/redis/filters_redis.py
> +def generic_query_redis(query: QueryParams, **kwargs) -> Dict[str, Any]:
👍

2020-12-04 19:14 UTC, Gleekzone commented on agave/collections/redis/helpers_redis.py
> +from rom import Column
👍

2020-12-09 01:03 UTC, matin requested changes
no

2020-12-09 01:03 UTC, closed without merging