Agave deps
cuenca-mx/agave pull request #21
Opened 2020-12-08 16:57 UTC by agarrido19

Fixes dependencies using the new pip resolver, also fixes another issue to really increase coverage

closes #12
closes #20

2020-12-08 18:35 UTC, alexviquez commented
@agarrido19 Hay que resolver conflictos y subir codecov

2020-12-09 17:49 UTC, felipaoo requested changes
review por slack :D

2020-12-09 18:00 UTC, felipaoo commented on agave/lib/mongoengine/enum_field.py
> +        return super(EnumField, self).prepare_query_value(  # pragma: no cover
para evitar hacer tests de enum_field mejor debemos usar este paquete: https://pypi.org/project/extras_mongoengine/ 
abrí un issue para aplicarlo
https://github.com/cuenca-mx/agave/issues/23

2020-12-10 23:48 UTC, agarrido19 commented
Comentarios resueltos por slack :D

2020-12-11 00:23 UTC, felipaoo approved these changes

2020-12-11 00:23 UTC, merged