Add new uuid_field_account
cuenca-mx/agave pull request #66
Opened 2021-03-11 18:20 UTC by kerycdiaz

closes #65

2021-03-16 16:40 UTC, felipaoo requested changes

2021-03-16 16:40 UTC, felipaoo commented on agave/models/helpers.py
> +    text = f"{bank_code}{account_number}{user_id}"
podrías comentar porque es necesario esto? que funcionalidad te da que no te de llamando a `uuid_field('AC')`?

2021-03-17 22:32 UTC, kerycdiaz commented
cerrado porque se hará en oaxaca.

2021-03-19 01:06 UTC, felipaoo requested changes

2021-03-19 01:06 UTC, felipaoo commented on agave/models/helpers.py
> +def uuid_field_generic(prefix: str = '', **kwargs) -> str:
creo que `kwargs` no es tan descriptivo para el propósito de esta función. podría ser algo como `fields`

2021-03-19 16:29 UTC, kerycdiaz commented on agave/models/helpers.py
> +    sorted_text = ''.join(
listo

2021-03-19 16:34 UTC, felipaoo approved these changes

2021-03-19 16:36 UTC, merged