New cards
cuenca-mx/agave pull request #69
Opened 2021-03-22 23:31 UTC by ricardo8990

Agrega un campo al modelo base de `to_dict` llamado `url_reference`, con este campo podemos decidir si queremos que un objeto embebido tenga una URL como referencia o el objeto tal cual.

2021-03-23 18:21 UTC, alexviquez requested changes
Porque no mejor usas un header para definir si se va a consultar el contenido completo o solo se va a consultar el objeto principal, más los url, me refiero a algo como:

```json
headers = {"Content-Attributes":"uris"}
# ó
headers = {"Content-Attributes":"resources"}
```
eso haría que en otras librerías con el hecho de agregar ese header podamos descargar los objetos anidados.

2021-03-23 18:22 UTC, alexviquez commented
y quitar los prints

2021-03-23 19:50 UTC, ricardo8990 commented
> Porque no mejor usas un header para definir si se va a consultar el contenido completo o solo se va a consultar el objeto principal, más los url, me refiero a algo como:
> 
> ```json
> headers = {"Content-Attributes":"uris"}
> # ó
> headers = {"Content-Attributes":"resources"}
> ```
> 
> eso haría que en otras librerías con el hecho de agregar ese header podamos descargar los objetos anidados.

Creo que si es algo que podríamos agregar, aunque este caso sería el primer paso para llegar a ello. Ya que sería durante los blueprints que de acuerdo al tipo de header se debería de mandar el parámetro o no. En este caso agregué el parámetro ya que los `CardActivation` de `Cuenca` siempre deben incluir el objeto embebido, por otro lado, no sé si eso haría que se tengan que estar editando los headers para diferentes peticiones, por ejemplo, alguien usando `cuenca-python` tendría que hacer algo como:

```python
import cuenca

# Poner headers como resources
cuenca.http.session.headers['Content-Attributes'] = 'resources'
card_activation = CardActivation.create(...)
card = card_activation.card

# Para obtener ahora sus card_transactions, regresar los headers como estaban
cuenca.http.session.headers['Content-Attributes'] = 'uris'
card_activation = CardTransactions.all()
```

2021-03-23 21:39 UTC, alexviquez commented
> > Porque no mejor usas un header para definir si se va a consultar el contenido completo o solo se va a consultar el objeto principal, más los url, me refiero a algo como:
> > ```json
> > headers = {"Content-Attributes":"uris"}
> > # ó
> > headers = {"Content-Attributes":"resources"}
> > ```
> > 
> > 
> > eso haría que en otras librerías con el hecho de agregar ese header podamos descargar los objetos anidados.
> 
> Creo que si es algo que podríamos agregar, aunque este caso sería el primer paso para llegar a ello. Ya que sería durante los blueprints que de acuerdo al tipo de header se debería de mandar el parámetro o no. En este caso agregué el parámetro ya que los `CardActivation` de `Cuenca` siempre deben incluir el objeto embebido, por otro lado, no sé si eso haría que se tengan que estar editando los headers para diferentes peticiones, por ejemplo, alguien usando `cuenca-python` tendría que hacer algo como:
> 
> ```python
> import cuenca
> 
> # Poner headers como resources
> cuenca.http.session.headers['Content-Attributes'] = 'resources'
> card_activation = CardActivation.create(...)
> card = card_activation.card
> 
> # Para obtener ahora sus card_transactions, regresar los headers como estaban
> cuenca.http.session.headers['Content-Attributes'] = 'uris'
> card_activation = CardTransactions.all()
> ```

pero podrías hacerlo desde el configure no?, hay recursos que en realidad no harían nada distinto como card_transactions ya que en el to_dict de mongo no tiene campos que tengan referencias, pero del lado del cliente como cuenca-dart o cuenca-node en un futuro sería valioso en un solo request obtener el contexto completo de un balance-entrie o así

2021-03-24 06:14 UTC, ricardo8990 commented
> > > Porque no mejor usas un header para definir si se va a consultar el contenido completo o solo se va a consultar el objeto principal, más los url, me refiero a algo como:
> > > ```json
> > > headers = {"Content-Attributes":"uris"}
> > > # ó
> > > headers = {"Content-Attributes":"resources"}
> > > ```
> > > 
> > > 
> > > eso haría que en otras librerías con el hecho de agregar ese header podamos descargar los objetos anidados.
> > 
> > 
> > Creo que si es algo que podríamos agregar, aunque este caso sería el primer paso para llegar a ello. Ya que sería durante los blueprints que de acuerdo al tipo de header se debería de mandar el parámetro o no. En este caso agregué el parámetro ya que los `CardActivation` de `Cuenca` siempre deben incluir el objeto embebido, por otro lado, no sé si eso haría que se tengan que estar editando los headers para diferentes peticiones, por ejemplo, alguien usando `cuenca-python` tendría que hacer algo como:
> > ```python
> > import cuenca
> > 
> > # Poner headers como resources
> > cuenca.http.session.headers['Content-Attributes'] = 'resources'
> > card_activation = CardActivation.create(...)
> > card = card_activation.card
> > 
> > # Para obtener ahora sus card_transactions, regresar los headers como estaban
> > cuenca.http.session.headers['Content-Attributes'] = 'uris'
> > card_activation = CardTransactions.all()
> > ```
> 
> pero podrías hacerlo desde el configure no?, hay recursos que en realidad no harían nada distinto como card_transactions ya que en el to_dict de mongo no tiene campos que tengan referencias, pero del lado del cliente como cuenca-dart o cuenca-node en un futuro sería valioso en un solo request obtener el contexto completo de un balance-entrie o así

Regresé los archivos a cómo estaban, solo dejé la corrección del test que realmente no estaba probando algo en concreto.

2021-03-24 19:09 UTC, alexviquez approved these changes
ajustar las librerías y crear un issue para explorar el tema que platiccamos de los headers a futuro, incluso se me ocurre que podríamos no manejarlo del header, si no manejarlo desde la url tal y como jsonapi lo hace, es decir en el get añadir un `attributes=related_transaction, funding_instrument` y si no trae como atributo el campo, no hacer el fetch y dejar solo la url del recurso, en caso contrario crear el objeto anidado

2021-03-24 23:57 UTC, ricardo8990 commented
> ajustar las librerías y crear un issue para explorar el tema que platiccamos de los headers a futuro, incluso se me ocurre que podríamos no manejarlo del header, si no manejarlo desde la url tal y como jsonapi lo hace, es decir en el get añadir un `attributes=related_transaction, funding_instrument` y si no trae como atributo el campo, no hacer el fetch y dejar solo la url del recurso, en caso contrario crear el objeto anidado

Issue https://github.com/cuenca-mx/agave/issues/72 y librerías actualizadas

2021-03-25 00:00 UTC, kerycdiaz approved these changes

2021-03-25 00:01 UTC, alexviquez approved these changes
fierro

2021-03-25 00:01 UTC, merged